modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="Buizz"
description='''전투 중 즉시 경험치, 포획 경험치, 반응형 경험치 HUD를 제공합니다.'''

[[mixins]]
config="cobbleventure_experience.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="cobblemon"
type="required"
versionRange="${cobblemon_version_range}"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="cobbleventure_player_menu"
type="required"
versionRange="[1.6.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="cobblemonxpbar"
type="incompatible"
versionRange="[0,)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="fix_cobblemon_pokemon_experience"
type="incompatible"
versionRange="[0,)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="capture_xp"
type="incompatible"
versionRange="[0,)"
ordering="NONE"
side="BOTH"
