modLoader="javafml"
loaderVersion="[4,)"
license="All Rights Reserved"
[[mods]]
modId="cobbleventure_content_runtime"
version="1.0.0"
displayName="Cobbleventure Content Runtime"
description="External content loading and engine contract."
[[dependencies.cobbleventure_content_runtime]]
modId="neoforge"
type="required"
versionRange="[21.1.248,)"
ordering="NONE"
side="BOTH"
